# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    build: './db'
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: hello
    ports:
      - '5432:5432'



